### PR TITLE
fix heroku deploy button

### PR DESCRIPTION
**Pull request by DasCanard**

### CODE REVIEW

**Comment by fr0tt** [comment]
Thank you for your support ! Much appreciated !

However I'm not sure I unterstand your problem with the current implentation. 
At least in my browser clicking the button already redirects me to a setup of Benotes instead of just an ordinary login screen or something similiar (if you look closely at the URL).

I also tried to follow Herokus advice on implementing the button as stated here: https://devcenter.heroku.com/articles/heroku-button#using-an-implicit-template
"[...] allowing forks and branches of the repository to work properly without a change to the button href".
Meaning you can deploy e.g. your own fork or the dev branch as easily as using the master without any change.

**Comment by DasCanard** [comment]
With the old Button I will be stuck here: 
image

--- 

With new Button is it working again:
image

**Comment by fr0tt** [comment]
So I did some research and it seems you are not the only one with this problem (e.g. https://github.com/heroku/node-js-getting-started/issues/61). Although it's still a strange problem. (Maybe it has something to do with your firewall ?)

However using your solution would reduce the amount of use cases for the link so I implemented a different approach. 
Hope you like it.

**Comment by DasCanard** [comment]
Yeah this seems like a good solution

**Pull request closed without merging**
